server:
  port: 31002
spring:
    application:
      name: edu-online-manage-course #服务名称
    datasource:
      druid:
        url: jdbc:mysql://localhost:3306/edu_course?characterEncoding=utf-8
        username: root
        password: 305114
        driverClassName: com.mysql.jdbc.Driver
        initialSize: 5  #初始建立连接数量
        minIdle: 5  #最小连接数量
        maxActive: 20 #最大连接数量
        maxWait: 10000  #获取连接最大等待时间，毫秒
        testOnBorrow: true #申请连接时检测连接是否有效
        testOnReturn: false #归还连接时检测连接是否有效
        timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
        minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
pagehelper:
  helper-dialect: mysql #指定数据库类型
mybatis:
  typeAliasesPackage: edu.online.Entity
  mapperLocations: classpath:mapper/*.xml  #指定mapper.xml文件的位置（自定义路径）