server:
  port: 51000
spring:
  application:
    name: edu-online-fileserver #服务名称
  #mongodb配置
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: edu_cms
 #SpringMVC上传文件配置
  servlet:
    multipart:
    #默认支持文件上传.
      enabled: true
    #当文件达到多少时进行磁盘写入
      file-size-threshold: 0
    #上传文件的临时目录
      location:
     # 最大支持文件大小
      max-file-size: 1MB
     # 最大支持请求大小
      max-request-size: 30MB
edu:
  fastdfs:
    connect_timeout_in_seconds: 30
    network_timeout_in_seconds: 30
    charset: UTF-8
    tracker_servers: 192.168.8.128:22122 #虚拟机IP地址 多个 trackerServer中间以逗号分隔


