spring:
  application:
    name: edu-online-manage-cms #服务名称
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: edu_cms
  freemarker:
    cache: false
    settings:
      template_update_delay: 0
  rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest
      virtual-host: /
server:
  port: 31001
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
          defaultZone: http://localhost:10001/eureka/
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #指定实例id

