server:
  port: 41001
  servlet:
    context-path: /auth #根路径
spring:
    application:
      name: edu-online-oauth-oauth2 #服务名称
    datasource:
          druid:
              url: jdbc:mysql://localhost:3306/edu_ucenter?characterEncoding=utf-8
              username: root
              password: 305114
              driverClassName: com.mysql.jdbc.Driver
              initialSize: 5  #初始建立连接数量
              minIdle: 5  #最小连接数量
              maxActive: 20 #最大连接数量
              maxWait: 10000  #获取连接最大等待时间，毫秒
              testOnBorrow: true #申请连接时检测连接是否有效
              testOnReturn: false #归还连接时检测连接是否有效
              timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
              minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
    redis: # redis 配置
      host: 127.0.0.1
      port: 6379
      timeout: 5000ms
      jedis:
        pool:
          max-active: 3
          max-idle: 3
          min-idle: 1
          max-wait: -1ms
auth:
  tokenValiditySeconds: 1200  #token存储到redis的过期时间
  clientId: XcWebApp #客户端id  oauth_client_details表中
  clientSecret: XcWebApp #客户端密码
  cookieDomain: localhost
  cookieMaxAge: -1

encrypt:   #由KeyProperties类 读取密钥的配置文件
  key-store:
    location: classpath:/edu.keystore #密钥路径
    secret: edukeystore #密钥库密码
    alias: eduonline #密钥别名
    password: eduonline #密钥密码
eureka:
   client:
     registerWithEureka: true #服务注册开关
     fetchRegistry: true #服务发现开关
     serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
       defaultZone: http://localhost:10001/eureka/
   instance:
     prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
     ip-address: 127.0.0.1
     instance-id: ${spring.application.name}:${server.port} #指定实例id