spring:
  application:
    name: edu-online-learning
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/edu_learning?characterEncoding=utf-8
      username: root
      password: 305114
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）

server:
  port: 60001
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
     defaultZone: http://eureka01:10001/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: ${spring.application.name}:${server.port}
pagehelper:
  helper-dialect: mysql
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: edu.online.Entity



